
PROC IMPORT
DATAFILE ="C:\Users\EmilyHong\Google 雲端硬碟\graduate\106A course\多變量分析\Homework 3\test.xlsx"
OUT= WORK
DBMS=EXCEL REPLACE;

RUN;

/*分訓練和測試*/
DATA TRAIN TEST;
  SET WORK;
  IF id <=523 THEN OUTPUT TRAIN;
  IF id >523 THEN OUTPUT TEST;
RUN;

PROC PRINT DATA=TRAIN; 
PROC PRINT DATA=TEST;

/* Discrimination Analysis */
/* class :y變數 */
/*PRIORS先驗機率  */
PROC DISCRIM DATA=train TESTDATA=test LIST LISTERR TESTLIST TESTLISTERR;
CLASS CNTTDHH;
VAR DRVRCNT HHFAMINC HHSIZE HHVEHCNT WRKCOUNT wchild retired;
 PRIORS '0'=.64 '1'=.36 ;
RUN;
/* Stepwise Discrimination Analysis */
PROC STEPDISC DATA=train FORWARD;
CLASS CNTTDHH;
VAR DRVRCNT HHFAMINC HHSIZE HHVEHCNT WRKCOUNT wchild retired;
RUN;
/* 根據逐步判別分析的結果，刪掉DRVRCNT及 HHVEHCNT 兩變數，留下其他變數，再做一次判別分析 */
PROC DISCRIM DATA=train TESTDATA=test LIST LISTERR TESTLIST TESTLISTERR;
CLASS CNTTDHH;
VAR HHFAMINC HHSIZE WRKCOUNT wchild retired;
 PRIORS '0'=.64 '1'=.36 ;
RUN;

